import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import GlobalLayout from "@/components/GlobalLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* NOTE ColorSchemeScript is to prevent FART (flash of inaccurate colour scheme) in SSR. `defaultColorScheme` in both ColorSchemeScript in MantineProvider must match */}
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider defaultColorScheme="auto">
          <GlobalLayout>{children}</GlobalLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
